/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JLabel;
import objetogeometrico.Rectangulo;

/**
 *
 * @author Usuario
 */
public class Rectangulo_ventana extends javax.swing.JFrame {

    /**
     * Creates new form Rectangulo_ventana
     */
    public Rectangulo_ventana() {
        initComponents();
        this.setLocationRelativeTo(null); //Poner la ventana en mitad de la pantalla
    }
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icono_matematicas.png")); //Colocar el icono en la barra de tareas
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_cerrar = new javax.swing.JButton();
        jLabel_encabezado = new javax.swing.JLabel();
        jButton_calcular_perimetro_rectangulo = new javax.swing.JButton();
        jTextField_base_perimetro_rectangulo = new javax.swing.JTextField();
        jTextField_altura_perimetro_rectangulo = new javax.swing.JTextField();
        jLabel_base_rectangulo1 = new javax.swing.JLabel();
        jLabel_altura_rectangulo1 = new javax.swing.JLabel();
        jLabel_resultado_perimetro_rectangulo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton_volver_menu = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel_copyright = new javax.swing.JLabel();
        jLabel_base_rectangulo = new javax.swing.JLabel();
        jLabel_altura_rectangulo = new javax.swing.JLabel();
        jButton_calcular_area_rectangulo = new javax.swing.JButton();
        jTextField_altura_area_rectangulo = new javax.swing.JTextField();
        jTextField_base_area_rectangulo = new javax.swing.JTextField();
        jLabel_area_encabezado = new javax.swing.JLabel();
        jLabel_resultado_area_rectangulo = new javax.swing.JLabel();
        jLabel_area_encabezado1 = new javax.swing.JLabel();
        jLabel_icon_info1 = new javax.swing.JLabel();
        jLabel_formula_area_rectangulo = new javax.swing.JLabel();
        jLabel_icon_info2 = new javax.swing.JLabel();
        jLabel_formula_perimetro_rectangulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_descripcion_area1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_descripcion_area = new javax.swing.JTextArea();
        jLabel_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_cerrar.setBackground(new java.awt.Color(183, 28, 28));
        jButton_cerrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_cerrar.setText("X");
        jButton_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, -1, -1));

        jLabel_encabezado.setFont(new java.awt.Font("Lemon/Milk", 1, 24)); // NOI18N
        jLabel_encabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_encabezado.setText("Rectangulo");
        jLabel_encabezado.setToolTipText("");
        getContentPane().add(jLabel_encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        jButton_calcular_perimetro_rectangulo.setBackground(new java.awt.Color(3, 169, 244));
        jButton_calcular_perimetro_rectangulo.setForeground(new java.awt.Color(255, 255, 255));
        jButton_calcular_perimetro_rectangulo.setText("Calcular");
        jButton_calcular_perimetro_rectangulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_calcular_perimetro_rectangulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_calcular_perimetro_rectanguloMouseClicked(evt);
            }
        });
        getContentPane().add(jButton_calcular_perimetro_rectangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 220, 40));
        getContentPane().add(jTextField_base_perimetro_rectangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 90, 40));
        getContentPane().add(jTextField_altura_perimetro_rectangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 90, 40));

        jLabel_base_rectangulo1.setText("Base:");
        getContentPane().add(jLabel_base_rectangulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, -1));

        jLabel_altura_rectangulo1.setText("Altura:");
        getContentPane().add(jLabel_altura_rectangulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, -1, -1));

        jLabel_resultado_perimetro_rectangulo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_resultado_perimetro_rectangulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_resultado_perimetro_rectangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel_resultado_perimetro_rectangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 180, 30));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 670, 10));

        jButton_volver_menu.setBackground(new java.awt.Color(33, 33, 33));
        jButton_volver_menu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton_volver_menu.setForeground(new java.awt.Color(255, 255, 255));
        jButton_volver_menu.setText("< Volver al menu");
        jButton_volver_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_volver_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_volver_menuMouseClicked(evt);
            }
        });
        getContentPane().add(jButton_volver_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 50, 370));

        jLabel_copyright.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel_copyright.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_copyright.setText("Copyright 2017  Albert E. Hidalgo Taveras. Todos los Derechos Reservados.");
        getContentPane().add(jLabel_copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 530, -1, -1));

        jLabel_base_rectangulo.setText("Base:");
        getContentPane().add(jLabel_base_rectangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel_altura_rectangulo.setText("Altura:");
        getContentPane().add(jLabel_altura_rectangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        jButton_calcular_area_rectangulo.setBackground(new java.awt.Color(3, 169, 244));
        jButton_calcular_area_rectangulo.setForeground(new java.awt.Color(255, 255, 255));
        jButton_calcular_area_rectangulo.setText("Calcular");
        jButton_calcular_area_rectangulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_calcular_area_rectangulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_calcular_area_rectanguloMouseClicked(evt);
            }
        });
        getContentPane().add(jButton_calcular_area_rectangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 220, 40));
        getContentPane().add(jTextField_altura_area_rectangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 90, 40));
        getContentPane().add(jTextField_base_area_rectangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 90, 40));

        jLabel_area_encabezado.setFont(new java.awt.Font("Lemon/Milk", 1, 18)); // NOI18N
        jLabel_area_encabezado.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_area_encabezado.setText("Perimetro");
        getContentPane().add(jLabel_area_encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, -1, -1));

        jLabel_resultado_area_rectangulo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_resultado_area_rectangulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_resultado_area_rectangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel_resultado_area_rectangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 170, 30));

        jLabel_area_encabezado1.setFont(new java.awt.Font("Lemon/Milk", 1, 18)); // NOI18N
        jLabel_area_encabezado1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_area_encabezado1.setText("AREA");
        getContentPane().add(jLabel_area_encabezado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        jLabel_icon_info1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/info_icon.png"))); // NOI18N
        getContentPane().add(jLabel_icon_info1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        jLabel_formula_area_rectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/area_rectangulo.png"))); // NOI18N
        getContentPane().add(jLabel_formula_area_rectangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 340, -1));

        jLabel_icon_info2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/info_icon.png"))); // NOI18N
        getContentPane().add(jLabel_icon_info2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, -1, -1));

        jLabel_formula_perimetro_rectangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/perimetro_rectangulo.png"))); // NOI18N
        getContentPane().add(jLabel_formula_perimetro_rectangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, -1, -1));

        jScrollPane2.setBorder(null);

        jTextArea_descripcion_area1.setEditable(false);
        jTextArea_descripcion_area1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea_descripcion_area1.setColumns(20);
        jTextArea_descripcion_area1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea_descripcion_area1.setRows(5);
        jTextArea_descripcion_area1.setText("El perímetro de un rectángulo es la suma de sus cuatro lados. \nComo el rectángulo tiene los lados iguales dos a dos, \nsu perímetro será el doble de la suma de dos lados contiguos\n(es decir, a y b).\n\n");
        jTextArea_descripcion_area1.setAutoscrolls(false);
        jTextArea_descripcion_area1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descripcion", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jTextArea_descripcion_area1.setFocusable(false);
        jTextArea_descripcion_area1.setRequestFocusEnabled(false);
        jTextArea_descripcion_area1.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(jTextArea_descripcion_area1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 380, 180));

        jScrollPane1.setBorder(null);

        jTextArea_descripcion_area.setEditable(false);
        jTextArea_descripcion_area.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea_descripcion_area.setColumns(20);
        jTextArea_descripcion_area.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea_descripcion_area.setRows(5);
        jTextArea_descripcion_area.setText("El área de un rectángulo se calcula a partir de los dos lados \ndiferentes (a y b). Es el producto de los dos lados contiguos \ndel rectángulo.\n\n");
        jTextArea_descripcion_area.setAutoscrolls(false);
        jTextArea_descripcion_area.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descripcion", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jTextArea_descripcion_area.setFocusable(false);
        jTextArea_descripcion_area.setRequestFocusEnabled(false);
        jTextArea_descripcion_area.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(jTextArea_descripcion_area);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 360, 180));

        jLabel_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_blanco.png"))); // NOI18N
        getContentPane().add(jLabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 990, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_cerrarActionPerformed

    private void jButton_volver_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_volver_menuMouseClicked
        // Volver al menu
        menu_principal menuprincipal = new menu_principal();
        menuprincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_volver_menuMouseClicked

    private void jButton_calcular_area_rectanguloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_calcular_area_rectanguloMouseClicked
        // Calcular el area del Rectangulo
        double resultado;
        //Convirtiendo los datos de entrada a double
        Double altura = new Double(this.jTextField_altura_area_rectangulo.getText()); 
        Double base = new Double (this.jTextField_base_area_rectangulo.getText()); 
        //Nuevo objeto de tipo cuadrado
        Rectangulo rectangulo = new Rectangulo(); 
        
        //Enviadno el valor a calcular al set del rectangulo
        rectangulo.setAltura(altura); 
        rectangulo.setBase(base); 
        resultado = rectangulo.calcularArea(); //Almacenando resultaod del calculo en una variable resultado

        String salida = String.valueOf(resultado); //Pasando el resultaod a string para luego imprimirlo en ventana por un campo label jframe

        this.jLabel_resultado_area_rectangulo.setText("Resultado: "+salida); //Enviando el resultado al label
    }//GEN-LAST:event_jButton_calcular_area_rectanguloMouseClicked

    private void jButton_calcular_perimetro_rectanguloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_calcular_perimetro_rectanguloMouseClicked
        // Calcular el perimetro del Rectangulo
        double resultado;
        //Convirtiendo los datos de entrada a double
        Double altura = new Double(this.jTextField_altura_perimetro_rectangulo.getText()); 
        Double base = new Double (this.jTextField_base_perimetro_rectangulo.getText()); 
        //Nuevo objeto de tipo cuadrado
        Rectangulo rectangulo = new Rectangulo(); 
        
        //Enviadno el valor a calcular al set del rectangulo
        rectangulo.setAltura(altura); 
        rectangulo.setBase(base); 
        resultado = rectangulo.calcularPerimetro(); //Almacenando resultaod del calculo en una variable resultado

        String salida = String.valueOf(resultado); //Pasando el resultaod a string para luego imprimirlo en ventana por un campo label jframe

        this.jLabel_resultado_perimetro_rectangulo.setText("Resultado: "+salida); //Enviando el resultado al label
    }//GEN-LAST:event_jButton_calcular_perimetro_rectanguloMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rectangulo_ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rectangulo_ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rectangulo_ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rectangulo_ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rectangulo_ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_calcular_area_rectangulo;
    private javax.swing.JButton jButton_calcular_perimetro_rectangulo;
    private javax.swing.JButton jButton_cerrar;
    private javax.swing.JButton jButton_volver_menu;
    private javax.swing.JLabel jLabel_altura_rectangulo;
    private javax.swing.JLabel jLabel_altura_rectangulo1;
    private javax.swing.JLabel jLabel_area_encabezado;
    private javax.swing.JLabel jLabel_area_encabezado1;
    private javax.swing.JLabel jLabel_base_rectangulo;
    private javax.swing.JLabel jLabel_base_rectangulo1;
    private javax.swing.JLabel jLabel_copyright;
    private javax.swing.JLabel jLabel_encabezado;
    private javax.swing.JLabel jLabel_fondo;
    private javax.swing.JLabel jLabel_formula_area_rectangulo;
    private javax.swing.JLabel jLabel_formula_perimetro_rectangulo;
    private javax.swing.JLabel jLabel_icon_info1;
    private javax.swing.JLabel jLabel_icon_info2;
    private javax.swing.JLabel jLabel_resultado_area_rectangulo;
    private javax.swing.JLabel jLabel_resultado_perimetro_rectangulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea_descripcion_area;
    private javax.swing.JTextArea jTextArea_descripcion_area1;
    private javax.swing.JTextField jTextField_altura_area_rectangulo;
    private javax.swing.JTextField jTextField_altura_perimetro_rectangulo;
    private javax.swing.JTextField jTextField_base_area_rectangulo;
    private javax.swing.JTextField jTextField_base_perimetro_rectangulo;
    // End of variables declaration//GEN-END:variables
}
