/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import objetogeometrico.Trapecio;

/**
 *
 * @author Usuario
 */
public class Trapecio_ventana extends javax.swing.JFrame {

    /**
     * Creates new form Trapecio_ventana
     */
    public Trapecio_ventana() {
        initComponents();
    this.setLocationRelativeTo(null); //Poner la ventana en mitad de la pantalla
    }
    
     public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icono_matematicas.png")); //Colocar el icono en la barra de tareas
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_cerrar = new javax.swing.JButton();
        jButton_volver_menu = new javax.swing.JButton();
        jLabel_encabezado = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel_area_encabezado = new javax.swing.JLabel();
        jLabel_area_encabezado1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_a2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel_a1 = new javax.swing.JLabel();
        jLabel_a = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel_icon_info1 = new javax.swing.JLabel();
        jTextField_altura_area = new javax.swing.JTextField();
        jTextField_ladoB = new javax.swing.JTextField();
        jTextField_ladoA = new javax.swing.JTextField();
        jButton_calcular_area_trapecio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton_calcular_area_trapecio1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_descripcion_area = new javax.swing.JTextArea();
        jLabel_resultado_area_trapecio = new javax.swing.JLabel();
        jLabel_forma_perimetro_trapecio = new javax.swing.JLabel();
        jLabel_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setMaximumSize(new java.awt.Dimension(800, 550));
        setMinimumSize(new java.awt.Dimension(800, 550));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_cerrar.setBackground(new java.awt.Color(183, 28, 28));
        jButton_cerrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_cerrar.setText("X");
        jButton_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, -1, -1));

        jButton_volver_menu.setBackground(new java.awt.Color(33, 33, 33));
        jButton_volver_menu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton_volver_menu.setForeground(new java.awt.Color(255, 255, 255));
        jButton_volver_menu.setText("< Volver al menu");
        jButton_volver_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_volver_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_volver_menuMouseClicked(evt);
            }
        });
        getContentPane().add(jButton_volver_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel_encabezado.setFont(new java.awt.Font("Lemon/Milk", 1, 24)); // NOI18N
        jLabel_encabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_encabezado.setText("trapecio");
        jLabel_encabezado.setToolTipText("");
        getContentPane().add(jLabel_encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 670, 10));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 10, 370));

        jLabel_area_encabezado.setFont(new java.awt.Font("Lemon/Milk", 1, 18)); // NOI18N
        jLabel_area_encabezado.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_area_encabezado.setText("AREA");
        getContentPane().add(jLabel_area_encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel_area_encabezado1.setFont(new java.awt.Font("Lemon/Milk", 1, 18)); // NOI18N
        jLabel_area_encabezado1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_area_encabezado1.setText("Perimetro");
        getContentPane().add(jLabel_area_encabezado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("b:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jLabel_a2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_a2.setText("c:");
        getContentPane().add(jLabel_a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, -1));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 60, 30));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 60, 30));

        jLabel_a1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_a1.setText("b:");
        getContentPane().add(jLabel_a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        jLabel_a.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_a.setText("a:");
        getContentPane().add(jLabel_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 60, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Altura:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel_icon_info1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/info_icon.png"))); // NOI18N
        getContentPane().add(jLabel_icon_info1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, -1, -1));
        getContentPane().add(jTextField_altura_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 50, 30));
        getContentPane().add(jTextField_ladoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 50, 30));
        getContentPane().add(jTextField_ladoA, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 50, 30));

        jButton_calcular_area_trapecio.setBackground(new java.awt.Color(3, 169, 244));
        jButton_calcular_area_trapecio.setForeground(new java.awt.Color(255, 255, 255));
        jButton_calcular_area_trapecio.setText("Calcular");
        jButton_calcular_area_trapecio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_calcular_area_trapecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_calcular_area_trapecioMouseClicked(evt);
            }
        });
        getContentPane().add(jButton_calcular_area_trapecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trapecio_figura.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 140));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/area_trapecio.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, -1, 50));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("a:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        jButton_calcular_area_trapecio1.setBackground(new java.awt.Color(3, 169, 244));
        jButton_calcular_area_trapecio1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_calcular_area_trapecio1.setText("Calcular");
        jButton_calcular_area_trapecio1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_calcular_area_trapecio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_calcular_area_trapecio1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton_calcular_area_trapecio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, -1, 40));

        jScrollPane1.setBorder(null);

        jTextArea_descripcion_area.setEditable(false);
        jTextArea_descripcion_area.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea_descripcion_area.setColumns(20);
        jTextArea_descripcion_area.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea_descripcion_area.setLineWrap(true);
        jTextArea_descripcion_area.setRows(5);
        jTextArea_descripcion_area.setText("El área de un trapecio se calcula a partir de su altura y los dos lados paralelos (a y b) o bases del trapecio. Es el resultado de multiplicar su altura (h) y la mediana del trapecio, que se obtiene como la media de las dos bases a y b: ");
        jTextArea_descripcion_area.setAutoscrolls(false);
        jTextArea_descripcion_area.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descripcion", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jTextArea_descripcion_area.setFocusable(false);
        jTextArea_descripcion_area.setRequestFocusEnabled(false);
        jTextArea_descripcion_area.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(jTextArea_descripcion_area);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 310, 170));

        jLabel_resultado_area_trapecio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(jLabel_resultado_area_trapecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 170, 30));

        jLabel_forma_perimetro_trapecio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/figura_perimetro_trapecio.png"))); // NOI18N
        getContentPane().add(jLabel_forma_perimetro_trapecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, -1, -1));

        jLabel_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_blanco.png"))); // NOI18N
        getContentPane().add(jLabel_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, -40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_cerrarActionPerformed

    private void jButton_volver_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_volver_menuMouseClicked
        // Volver al menu
        menu_principal menuprincipal = new menu_principal();
        menuprincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_volver_menuMouseClicked

    private void jButton_calcular_area_trapecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_calcular_area_trapecioMouseClicked
        // Calcular el perimetro del cuadrado
        // Calcular el area del cuadrado
        double resultado;
        Double ladoA = new Double(this.jTextField_ladoA.getText()); //Convirtiendo los datos de entrada a double       
        Double ladoB = new Double(this.jTextField_ladoB.getText()); //Convirtiendo los datos de entrada a double       
        Double altura = new Double(this.jTextField_altura_area.getText()); //Convirtiendo los datos de entrada a double       
        
        Trapecio trapecio = new Trapecio(); //Nuevo objeto de tipo cuadrado
        trapecio.setLadoA(ladoA); //Enviadno el valor a calcular al set 
        trapecio.setLadoB(ladoB); //Enviadno el valor a calcular al set
        trapecio.setAltura(altura); //Enviadno el valor a calcular al set
        resultado = trapecio.calcularArea(); //Almacenando resultaod del calculo en una variable resultado
        
        String salida = String.valueOf(resultado); //Pasando el resultaod a string para luego imprimirlo en ventana por un campo label jframe
        
        this.jLabel_resultado_area_trapecio.setText("Resultado: "+salida+" cm2"); //Enviando el resultado al label
    }//GEN-LAST:event_jButton_calcular_area_trapecioMouseClicked

    private void jButton_calcular_area_trapecio1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_calcular_area_trapecio1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_calcular_area_trapecio1MouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trapecio_ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trapecio_ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trapecio_ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trapecio_ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trapecio_ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_calcular_area_trapecio;
    private javax.swing.JButton jButton_calcular_area_trapecio1;
    private javax.swing.JButton jButton_cerrar;
    private javax.swing.JButton jButton_volver_menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_a;
    private javax.swing.JLabel jLabel_a1;
    private javax.swing.JLabel jLabel_a2;
    private javax.swing.JLabel jLabel_area_encabezado;
    private javax.swing.JLabel jLabel_area_encabezado1;
    private javax.swing.JLabel jLabel_encabezado;
    private javax.swing.JLabel jLabel_fondo;
    private javax.swing.JLabel jLabel_forma_perimetro_trapecio;
    private javax.swing.JLabel jLabel_icon_info1;
    private javax.swing.JLabel jLabel_resultado_area_trapecio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea_descripcion_area;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField_altura_area;
    private javax.swing.JTextField jTextField_ladoA;
    private javax.swing.JTextField jTextField_ladoB;
    // End of variables declaration//GEN-END:variables
}
