/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import objetogeometrico.Triangulo;

/**
 *
 * @author Usuario
 */
public class Triangulo_ventana extends javax.swing.JFrame {

    /**
     * Creates new form Triangulo_ventana
     */
    public Triangulo_ventana() {
        initComponents();
        jPanel_equilatero_ventana.setVisible(false);
        this.setLocationRelativeTo(null); //Poner la ventana en mitad de la pantalla
    }
    
     public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icono_matematicas.png")); //Colocar el icono en la barra de tareas
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_boton_isosceles = new javax.swing.JButton();
        jButton_volver_menu3 = new javax.swing.JButton();
        jButton_cerrar = new javax.swing.JButton();
        jLabel_encabezado = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel_copyright = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel_isosceles_ventana = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_figura_isosceles_equilatero = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_descripcion_area2 = new javax.swing.JTextArea();
        jLabel_equilatero_perimetro_formula1 = new javax.swing.JLabel();
        jButton_calcular_area_isosceles = new javax.swing.JButton();
        jTextField_ladoA_isosceles = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jTextField_ladoA_isosceles_perimetro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel_formula_isosceles = new javax.swing.JLabel();
        jLabel_resultado_area_isosceles = new javax.swing.JLabel();
        jLabel_resultado_perimetro_isosceles = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea_descripcion_area3 = new javax.swing.JTextArea();
        jLabel_encabezado3 = new javax.swing.JLabel();
        jLabel_figura_equilatero_perimetro1 = new javax.swing.JLabel();
        jLabel_resultado_perimetro_equilatero1 = new javax.swing.JLabel();
        jLabel_encabezado4 = new javax.swing.JLabel();
        jButton_calcular_perimetro_equilatero1 = new javax.swing.JButton();
        jTextField_ladoB_isosceles = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel_equilatero_ventana = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel_encabezado1 = new javax.swing.JLabel();
        jLabel_equilatero_perimetro_formula = new javax.swing.JLabel();
        jLabel_formula_equilatero = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_descripcion_area = new javax.swing.JTextArea();
        jTextField_ladoA_equilatero = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton_calcular_area_equilatero = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField_ladoA_equilatero_perimetro = new javax.swing.JTextField();
        jLabel_resultado_perimetro_equilatero = new javax.swing.JLabel();
        jButton_calcular_perimetro_equilatero = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_descripcion_area1 = new javax.swing.JTextArea();
        jLabel_encabezado2 = new javax.swing.JLabel();
        jLabel_resultado_area_equilatero = new javax.swing.JLabel();
        jLabel_figura_triangulo_equilatero = new javax.swing.JLabel();
        jLabel_figura_equilatero_perimetro = new javax.swing.JLabel();
        jLabel_fondo_blanco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(930, 550));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(930, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_boton_isosceles.setBackground(new java.awt.Color(63, 81, 181));
        jButton_boton_isosceles.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton_boton_isosceles.setForeground(new java.awt.Color(255, 255, 255));
        jButton_boton_isosceles.setText("Isosceles");
        jButton_boton_isosceles.setToolTipText("Triangulo que tiene todos sus lagos iguales.");
        jButton_boton_isosceles.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_boton_isosceles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_boton_isoscelesMouseClicked(evt);
            }
        });
        jButton_boton_isosceles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_boton_isoscelesActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_boton_isosceles, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 190, 60));

        jButton_volver_menu3.setBackground(new java.awt.Color(33, 33, 33));
        jButton_volver_menu3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton_volver_menu3.setForeground(new java.awt.Color(255, 255, 255));
        jButton_volver_menu3.setText("< Volver al menu");
        jButton_volver_menu3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_volver_menu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_volver_menu3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton_volver_menu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton_cerrar.setBackground(new java.awt.Color(183, 28, 28));
        jButton_cerrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_cerrar.setText("X");
        jButton_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, -1, -1));

        jLabel_encabezado.setFont(new java.awt.Font("Lemon/Milk", 1, 24)); // NOI18N
        jLabel_encabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_encabezado.setText("Triangulo");
        jLabel_encabezado.setToolTipText("");
        getContentPane().add(jLabel_encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 670, 10));

        jLabel_copyright.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel_copyright.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_copyright.setText("Copyright 2018 Albert E. Hidalgo Taveras. Todos los Derechos Reservados.");
        getContentPane().add(jLabel_copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, -1, -1));

        jButton1.setBackground(new java.awt.Color(63, 81, 181));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Equilatero");
        jButton1.setToolTipText("Triangulo que tiene todos sus lagos iguales.");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 190, 60));

        jPanel_isosceles_ventana.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_isosceles_ventana.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel_isosceles_ventana.setFocusCycleRoot(true);
        jPanel_isosceles_ventana.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Triangulo Isosceles");
        jPanel_isosceles_ventana.add(jLabel1);
        jLabel1.setBounds(380, 0, 230, 24);

        jLabel_figura_isosceles_equilatero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/triangulos/isosceles_figura.jpg"))); // NOI18N
        jPanel_isosceles_ventana.add(jLabel_figura_isosceles_equilatero);
        jLabel_figura_isosceles_equilatero.setBounds(20, 10, 170, 179);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("a:");
        jPanel_isosceles_ventana.add(jLabel4);
        jLabel4.setBounds(20, 200, 17, 24);

        jScrollPane3.setBorder(null);

        jTextArea_descripcion_area2.setEditable(false);
        jTextArea_descripcion_area2.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea_descripcion_area2.setColumns(20);
        jTextArea_descripcion_area2.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea_descripcion_area2.setLineWrap(true);
        jTextArea_descripcion_area2.setRows(5);
        jTextArea_descripcion_area2.setText("El triángulo equilátero tiene los tres lados iguales, por lo que su perímetro será tres veces la longitud de uno de sus lados (a).");
        jTextArea_descripcion_area2.setWrapStyleWord(true);
        jTextArea_descripcion_area2.setAutoscrolls(false);
        jTextArea_descripcion_area2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descripcion", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jTextArea_descripcion_area2.setFocusable(false);
        jTextArea_descripcion_area2.setRequestFocusEnabled(false);
        jTextArea_descripcion_area2.setVerifyInputWhenFocusTarget(false);
        jScrollPane3.setViewportView(jTextArea_descripcion_area2);

        jPanel_isosceles_ventana.add(jScrollPane3);
        jScrollPane3.setBounds(690, 100, 230, 130);

        jLabel_equilatero_perimetro_formula1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/triangulos/triangulo_equilatero_perimetro_formula.jpg"))); // NOI18N
        jPanel_isosceles_ventana.add(jLabel_equilatero_perimetro_formula1);
        jLabel_equilatero_perimetro_formula1.setBounds(720, 230, 173, 28);

        jButton_calcular_area_isosceles.setBackground(new java.awt.Color(3, 169, 244));
        jButton_calcular_area_isosceles.setForeground(new java.awt.Color(255, 255, 255));
        jButton_calcular_area_isosceles.setText("Calcular");
        jButton_calcular_area_isosceles.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_calcular_area_isosceles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_calcular_area_isoscelesMouseClicked(evt);
            }
        });
        jPanel_isosceles_ventana.add(jButton_calcular_area_isosceles);
        jButton_calcular_area_isosceles.setBounds(40, 270, 160, 40);
        jPanel_isosceles_ventana.add(jTextField_ladoA_isosceles);
        jTextField_ladoA_isosceles.setBounds(40, 200, 60, 30);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel_isosceles_ventana.add(jSeparator3);
        jSeparator3.setBounds(470, 40, 20, 290);
        jPanel_isosceles_ventana.add(jTextField_ladoA_isosceles_perimetro);
        jTextField_ladoA_isosceles_perimetro.setBounds(560, 200, 60, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("a:");
        jPanel_isosceles_ventana.add(jLabel5);
        jLabel5.setBounds(540, 190, 17, 24);

        jLabel_formula_isosceles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/triangulos/isosceles_formula.jpg"))); // NOI18N
        jPanel_isosceles_ventana.add(jLabel_formula_isosceles);
        jLabel_formula_isosceles.setBounds(250, 220, 193, 92);

        jLabel_resultado_area_isosceles.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_resultado_area_isosceles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_resultado_area_isosceles.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel_isosceles_ventana.add(jLabel_resultado_area_isosceles);
        jLabel_resultado_area_isosceles.setBounds(30, 240, 190, 30);

        jLabel_resultado_perimetro_isosceles.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_resultado_perimetro_isosceles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_resultado_perimetro_isosceles.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel_isosceles_ventana.add(jLabel_resultado_perimetro_isosceles);
        jLabel_resultado_perimetro_isosceles.setBounds(500, 240, 190, 30);

        jScrollPane4.setBorder(null);

        jTextArea_descripcion_area3.setEditable(false);
        jTextArea_descripcion_area3.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea_descripcion_area3.setColumns(20);
        jTextArea_descripcion_area3.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea_descripcion_area3.setLineWrap(true);
        jTextArea_descripcion_area3.setRows(5);
        jTextArea_descripcion_area3.setText("El área de un triángulo isósceles, como en todo triángulo, será un medio de la base (b) por su altura. En el triángulo isósceles se calcula mediante la siguiente fórmula:");
        jTextArea_descripcion_area3.setWrapStyleWord(true);
        jTextArea_descripcion_area3.setAutoscrolls(false);
        jTextArea_descripcion_area3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descripcion", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jTextArea_descripcion_area3.setFocusable(false);
        jTextArea_descripcion_area3.setRequestFocusEnabled(false);
        jTextArea_descripcion_area3.setVerifyInputWhenFocusTarget(false);
        jScrollPane4.setViewportView(jTextArea_descripcion_area3);

        jPanel_isosceles_ventana.add(jScrollPane4);
        jScrollPane4.setBounds(230, 100, 230, 160);

        jLabel_encabezado3.setFont(new java.awt.Font("Lemon/Milk", 1, 24)); // NOI18N
        jLabel_encabezado3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_encabezado3.setText("PERIMETRO");
        jLabel_encabezado3.setToolTipText("");
        jPanel_isosceles_ventana.add(jLabel_encabezado3);
        jLabel_encabezado3.setBounds(620, 20, 269, 40);

        jLabel_figura_equilatero_perimetro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/triangulos/triangulo_equilatero_perimetro_figura.jpg"))); // NOI18N
        jPanel_isosceles_ventana.add(jLabel_figura_equilatero_perimetro1);
        jLabel_figura_equilatero_perimetro1.setBounds(490, 10, 189, 180);

        jLabel_resultado_perimetro_equilatero1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_resultado_perimetro_equilatero1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_resultado_perimetro_equilatero1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel_isosceles_ventana.add(jLabel_resultado_perimetro_equilatero1);
        jLabel_resultado_perimetro_equilatero1.setBounds(500, 230, 190, 30);

        jLabel_encabezado4.setFont(new java.awt.Font("Lemon/Milk", 1, 24)); // NOI18N
        jLabel_encabezado4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_encabezado4.setText("AREA");
        jLabel_encabezado4.setToolTipText("");
        jPanel_isosceles_ventana.add(jLabel_encabezado4);
        jLabel_encabezado4.setBounds(290, 10, 131, 40);

        jButton_calcular_perimetro_equilatero1.setBackground(new java.awt.Color(3, 169, 244));
        jButton_calcular_perimetro_equilatero1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_calcular_perimetro_equilatero1.setText("Calcular");
        jButton_calcular_perimetro_equilatero1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_calcular_perimetro_equilatero1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_calcular_perimetro_equilatero1MouseClicked(evt);
            }
        });
        jPanel_isosceles_ventana.add(jButton_calcular_perimetro_equilatero1);
        jButton_calcular_perimetro_equilatero1.setBounds(510, 270, 160, 40);
        jPanel_isosceles_ventana.add(jTextField_ladoB_isosceles);
        jTextField_ladoB_isosceles.setBounds(140, 200, 60, 30);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("b:");
        jPanel_isosceles_ventana.add(jLabel6);
        jLabel6.setBounds(120, 200, 18, 24);

        getContentPane().add(jPanel_isosceles_ventana, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 180, 1010, 340));

        jPanel_equilatero_ventana.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_equilatero_ventana.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel_equilatero_ventana.setFocusCycleRoot(true);
        jPanel_equilatero_ventana.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Triangulo Equilatero");
        jPanel_equilatero_ventana.add(jLabel7);
        jLabel7.setBounds(370, 0, 180, 30);

        jLabel_encabezado1.setFont(new java.awt.Font("Lemon/Milk", 1, 24)); // NOI18N
        jLabel_encabezado1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_encabezado1.setText("PERIMETRO");
        jLabel_encabezado1.setToolTipText("");
        jPanel_equilatero_ventana.add(jLabel_encabezado1);
        jLabel_encabezado1.setBounds(620, 20, 269, 40);

        jLabel_equilatero_perimetro_formula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/triangulos/triangulo_equilatero_perimetro_formula.jpg"))); // NOI18N
        jPanel_equilatero_ventana.add(jLabel_equilatero_perimetro_formula);
        jLabel_equilatero_perimetro_formula.setBounds(720, 210, 173, 28);

        jLabel_formula_equilatero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/triangulos/triangulo_equilatero_formula.jpg"))); // NOI18N
        jPanel_equilatero_ventana.add(jLabel_formula_equilatero);
        jLabel_formula_equilatero.setBounds(270, 260, 148, 60);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("a:");
        jPanel_equilatero_ventana.add(jLabel2);
        jLabel2.setBounds(70, 200, 17, 24);

        jScrollPane1.setBorder(null);

        jTextArea_descripcion_area.setEditable(false);
        jTextArea_descripcion_area.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea_descripcion_area.setColumns(20);
        jTextArea_descripcion_area.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea_descripcion_area.setLineWrap(true);
        jTextArea_descripcion_area.setRows(5);
        jTextArea_descripcion_area.setText("El triángulo equilátero tiene los tres lados iguales, por lo que su perímetro será tres veces la longitud de uno de sus lados (a).");
        jTextArea_descripcion_area.setWrapStyleWord(true);
        jTextArea_descripcion_area.setAutoscrolls(false);
        jTextArea_descripcion_area.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descripcion", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jTextArea_descripcion_area.setFocusable(false);
        jTextArea_descripcion_area.setRequestFocusEnabled(false);
        jTextArea_descripcion_area.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(jTextArea_descripcion_area);

        jPanel_equilatero_ventana.add(jScrollPane1);
        jScrollPane1.setBounds(690, 100, 230, 130);
        jPanel_equilatero_ventana.add(jTextField_ladoA_equilatero);
        jTextField_ladoA_equilatero.setBounds(90, 200, 60, 30);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel_equilatero_ventana.add(jSeparator1);
        jSeparator1.setBounds(470, 60, 20, 270);

        jButton_calcular_area_equilatero.setBackground(new java.awt.Color(3, 169, 244));
        jButton_calcular_area_equilatero.setForeground(new java.awt.Color(255, 255, 255));
        jButton_calcular_area_equilatero.setText("Calcular");
        jButton_calcular_area_equilatero.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_calcular_area_equilatero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_calcular_area_equilateroMouseClicked(evt);
            }
        });
        jPanel_equilatero_ventana.add(jButton_calcular_area_equilatero);
        jButton_calcular_area_equilatero.setBounds(40, 270, 160, 40);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("a:");
        jPanel_equilatero_ventana.add(jLabel3);
        jLabel3.setBounds(540, 190, 17, 24);
        jPanel_equilatero_ventana.add(jTextField_ladoA_equilatero_perimetro);
        jTextField_ladoA_equilatero_perimetro.setBounds(560, 200, 60, 30);

        jLabel_resultado_perimetro_equilatero.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_resultado_perimetro_equilatero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_resultado_perimetro_equilatero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel_equilatero_ventana.add(jLabel_resultado_perimetro_equilatero);
        jLabel_resultado_perimetro_equilatero.setBounds(500, 230, 190, 30);

        jButton_calcular_perimetro_equilatero.setBackground(new java.awt.Color(3, 169, 244));
        jButton_calcular_perimetro_equilatero.setForeground(new java.awt.Color(255, 255, 255));
        jButton_calcular_perimetro_equilatero.setText("Calcular");
        jButton_calcular_perimetro_equilatero.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_calcular_perimetro_equilatero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_calcular_perimetro_equilateroMouseClicked(evt);
            }
        });
        jPanel_equilatero_ventana.add(jButton_calcular_perimetro_equilatero);
        jButton_calcular_perimetro_equilatero.setBounds(510, 270, 160, 40);

        jScrollPane2.setBorder(null);

        jTextArea_descripcion_area1.setEditable(false);
        jTextArea_descripcion_area1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea_descripcion_area1.setColumns(20);
        jTextArea_descripcion_area1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea_descripcion_area1.setLineWrap(true);
        jTextArea_descripcion_area1.setRows(5);
        jTextArea_descripcion_area1.setText("El área de un triángulo equilátero, \ncomo en todo triángulo, será un\n medio de la base (a) por su altura.\n\nEl triángulo equilátero tiene los tres lados iguales. En este caso, el área viene definida por la siguiente fórmula:\n");
        jTextArea_descripcion_area1.setWrapStyleWord(true);
        jTextArea_descripcion_area1.setAutoscrolls(false);
        jTextArea_descripcion_area1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descripcion", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jTextArea_descripcion_area1.setFocusable(false);
        jTextArea_descripcion_area1.setRequestFocusEnabled(false);
        jTextArea_descripcion_area1.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(jTextArea_descripcion_area1);

        jPanel_equilatero_ventana.add(jScrollPane2);
        jScrollPane2.setBounds(230, 100, 243, 190);

        jLabel_encabezado2.setFont(new java.awt.Font("Lemon/Milk", 1, 24)); // NOI18N
        jLabel_encabezado2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_encabezado2.setText("AREA");
        jLabel_encabezado2.setToolTipText("");
        jPanel_equilatero_ventana.add(jLabel_encabezado2);
        jLabel_encabezado2.setBounds(290, 10, 131, 40);

        jLabel_resultado_area_equilatero.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel_resultado_area_equilatero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_resultado_area_equilatero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel_equilatero_ventana.add(jLabel_resultado_area_equilatero);
        jLabel_resultado_area_equilatero.setBounds(30, 230, 190, 30);

        jLabel_figura_triangulo_equilatero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/triangulos/triangulo_equilatero_figura.jpg"))); // NOI18N
        jPanel_equilatero_ventana.add(jLabel_figura_triangulo_equilatero);
        jLabel_figura_triangulo_equilatero.setBounds(20, 10, 230, 185);

        jLabel_figura_equilatero_perimetro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/triangulos/triangulo_equilatero_perimetro_figura.jpg"))); // NOI18N
        jPanel_equilatero_ventana.add(jLabel_figura_equilatero_perimetro);
        jLabel_figura_equilatero_perimetro.setBounds(490, 10, 189, 180);

        getContentPane().add(jPanel_equilatero_ventana, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 180, 1010, 340));

        jLabel_fondo_blanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_blanco.png"))); // NOI18N
        jLabel_fondo_blanco.setOpaque(true);
        getContentPane().add(jLabel_fondo_blanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_volver_menu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_volver_menu3MouseClicked
        // Volver al menu
        menu_principal menuprincipal = new menu_principal();
        menuprincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton_volver_menu3MouseClicked

    private void jButton_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_cerrarActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
            jPanel_equilatero_ventana.setVisible(true);
            jPanel_isosceles_ventana.setVisible(false);
            
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_boton_isoscelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_boton_isoscelesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_boton_isoscelesActionPerformed

    private void jButton_calcular_perimetro_equilateroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_calcular_perimetro_equilateroMouseClicked
        // Calcular el perimetro del triangulo equilatero
        double resultado;
        //Convirtiendo los datos de entrada a double
        Double ladoA = new Double(this.jTextField_ladoA_equilatero_perimetro.getText());
        //Nuevo objeto de tipo cuadrado
        Triangulo triangulo = new Triangulo();
        triangulo.setTipo_triangulo("equilatero");
        //Enviadno el valor a calcular al set del triangulo equilatero
        triangulo.setLadoA(ladoA);
        resultado = triangulo.calcularPerimetro();//Almacenando resultaod del calculo en una variable resultado

        String salida = String.valueOf(resultado); //Pasando el resultaod a string para luego imprimirlo en ventana por un campo label jframe

        this.jLabel_resultado_perimetro_equilatero.setText("Resultado: "+salida+"cm"); //Enviando el resultado al label
    }//GEN-LAST:event_jButton_calcular_perimetro_equilateroMouseClicked

    private void jButton_calcular_area_equilateroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_calcular_area_equilateroMouseClicked
        // Calcular el area del triangulo equilatero
        double resultado;
        //Convirtiendo los datos de entrada a double
        Double ladoA = new Double(this.jTextField_ladoA_equilatero.getText());
        //Nuevo objeto de tipo cuadrado
        Triangulo triangulo = new Triangulo();
        triangulo.setTipo_triangulo("equilatero");
        //Enviadno el valor a calcular al set del triangulo equilatero
        triangulo.setLadoA(ladoA);
        resultado = triangulo.calcularArea();//Almacenando resultaod del calculo en una variable resultado

        String salida = String.valueOf(resultado); //Pasando el resultaod a string para luego imprimirlo en ventana por un campo label jframe

        this.jLabel_resultado_area_equilatero.setText("Resultado: "+salida+"cm2"); //Enviando el resultado al label
    }//GEN-LAST:event_jButton_calcular_area_equilateroMouseClicked

    private void jButton_boton_isoscelesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_boton_isoscelesMouseClicked
        jPanel_equilatero_ventana.setVisible(false);
            jPanel_isosceles_ventana.setVisible(true);
    }//GEN-LAST:event_jButton_boton_isoscelesMouseClicked

    private void jButton_calcular_perimetro_equilatero1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_calcular_perimetro_equilatero1MouseClicked
        // Calcular el area del triangulo isosceles
        double resultado;
        //Convirtiendo los datos de entrada a double
        Double ladoA = new Double(this.jTextField_ladoA_isosceles_perimetro.getText());
        //Nuevo objeto de tipo cuadrado
        Triangulo triangulo = new Triangulo();
        triangulo.setTipo_triangulo("isosceles");
        //Enviadno el valor a calcular al set del triangulo equilatero
        triangulo.setLadoA(ladoA);
        resultado = triangulo.calcularPerimetro();//Almacenando resultaod del calculo en una variable resultado

        String salida = String.valueOf(resultado); //Pasando el resultaod a string para luego imprimirlo en ventana por un campo label jframe

        this.jLabel_resultado_perimetro_isosceles.setText("Resultado: "+salida+"cm2"); //Enviando el resultado al label
    }//GEN-LAST:event_jButton_calcular_perimetro_equilatero1MouseClicked

    private void jButton_calcular_area_isoscelesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_calcular_area_isoscelesMouseClicked
        // Calcular el area del triangulo isosceles
        double resultado;
        //Convirtiendo los datos de entrada a double
        Double ladoA = new Double(this.jTextField_ladoA_isosceles.getText());
        Double ladoB = new Double(this.jTextField_ladoB_isosceles.getText());
        //Nuevo objeto de tipo cuadrado
        Triangulo triangulo = new Triangulo();
        triangulo.setTipo_triangulo("isosceles");
        //Enviadno el valor a calcular al set del triangulo equilatero
        triangulo.setLadoA(ladoA);
        triangulo.setLadoB(ladoB);
        resultado = triangulo.calcularArea();//Almacenando resultaod del calculo en una variable resultado

        String salida = String.valueOf(resultado); //Pasando el resultaod a string para luego imprimirlo en ventana por un campo label jframe

        this.jLabel_resultado_area_isosceles.setText("Resultado: "+salida+"cm2"); //Enviando el resultado al label
    }//GEN-LAST:event_jButton_calcular_area_isoscelesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try { 
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Triangulo_ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Triangulo_ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Triangulo_ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Triangulo_ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Triangulo_ventana().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_boton_isosceles;
    private javax.swing.JButton jButton_calcular_area_equilatero;
    private javax.swing.JButton jButton_calcular_area_isosceles;
    private javax.swing.JButton jButton_calcular_perimetro_equilatero;
    private javax.swing.JButton jButton_calcular_perimetro_equilatero1;
    private javax.swing.JButton jButton_cerrar;
    private javax.swing.JButton jButton_volver_menu3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_copyright;
    private javax.swing.JLabel jLabel_encabezado;
    private javax.swing.JLabel jLabel_encabezado1;
    private javax.swing.JLabel jLabel_encabezado2;
    private javax.swing.JLabel jLabel_encabezado3;
    private javax.swing.JLabel jLabel_encabezado4;
    private javax.swing.JLabel jLabel_equilatero_perimetro_formula;
    private javax.swing.JLabel jLabel_equilatero_perimetro_formula1;
    private javax.swing.JLabel jLabel_figura_equilatero_perimetro;
    private javax.swing.JLabel jLabel_figura_equilatero_perimetro1;
    private javax.swing.JLabel jLabel_figura_isosceles_equilatero;
    private javax.swing.JLabel jLabel_figura_triangulo_equilatero;
    private javax.swing.JLabel jLabel_fondo_blanco;
    private javax.swing.JLabel jLabel_formula_equilatero;
    private javax.swing.JLabel jLabel_formula_isosceles;
    private javax.swing.JLabel jLabel_resultado_area_equilatero;
    private javax.swing.JLabel jLabel_resultado_area_isosceles;
    private javax.swing.JLabel jLabel_resultado_perimetro_equilatero;
    private javax.swing.JLabel jLabel_resultado_perimetro_equilatero1;
    private javax.swing.JLabel jLabel_resultado_perimetro_isosceles;
    private javax.swing.JPanel jPanel_equilatero_ventana;
    private javax.swing.JPanel jPanel_isosceles_ventana;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea_descripcion_area;
    private javax.swing.JTextArea jTextArea_descripcion_area1;
    private javax.swing.JTextArea jTextArea_descripcion_area2;
    private javax.swing.JTextArea jTextArea_descripcion_area3;
    private javax.swing.JTextField jTextField_ladoA_equilatero;
    private javax.swing.JTextField jTextField_ladoA_equilatero_perimetro;
    private javax.swing.JTextField jTextField_ladoA_isosceles;
    private javax.swing.JTextField jTextField_ladoA_isosceles_perimetro;
    private javax.swing.JTextField jTextField_ladoB_isosceles;
    // End of variables declaration//GEN-END:variables
}
